### PR TITLE
fix object_usage_linter() XPath for `assign()` and `setMethod()`

### LINKED ISSUE #1322: `object_usage_linter()` tries too many assignments
Seen in our own package when running `lint_package()`:

```
..........Warning in formals(fun) : argument is not a function
Warning in body(fun) : argument is not a function
Warning in formals(fun) : argument is not a function
Warning in body(fun) : argument is not a function
...................................................Warning in formals(fun) : argument is not a function
Warning in body(fun) : argument is not a function
................................................................................................................................................
```

The reason is the XPath for `object_usage_linter()` finds e.g.

```r
assign(
    envir = cache,
    x = digest_content(linters, filename),
    value = lints,
    inherits = FALSE
  )
```

which is not a function assignment.

### PR DESCRIPTION
**Pull request by AshesITR**
fixes #1322

### CODE REVIEW

**Comment by MichaelChirico** [comment]
tests?

**Comment by AshesITR** [comment]
will add.

**Comment by AshesITR** [comment]
@MichaelChirico good call. Turns out neither `assign()` nor `setMethod()` were tested before and `setMethod()` was dysfunctional because it takes the function as the third positional argument and not the second.

**Comment by AshesITR** [comment]
NB: add info to #834 about the fix to `setMethods()` - that was not working in 2.0.1 either.

**Review by MichaelChirico — APPROVED** [review]
